### ISSUE TITLE
CSS Color System

### ISSUE THREAD

**Issue by jacobxperez** [jacobxperez/rams#9]
We need to develop a color system that uses CSS variables.

**Comment by Mstanic05** [comment]
Can you assign this to me!

**Comment by jacobxperez** [comment]
@Mstanic05 Thank you so much for being interested in this project. Rams currently lacks any coherent color system and this has created a couple of problems. I haven't been able to create solution because I been busy working on the typeface [Atkinson Hyperlegible Pro](https://github.com/jacobxperez/atkinson-hyperlegible-pro) which ships with Rams. I been looking for a CSS Variable color system solution which can easily be applied to the PostCSS variables without the need to touch the [core](https://github.com/jacobxperez/rams/tree/master/src/css/core) files. I have created a couple of color variables in [var.css](https://github.com/jacobxperez/rams/blob/master/src/css/var.css) however as you can tell this is not a complete solution. I am curious to know what type of solution you have in mind. Please let me know if you have any questions from me to answer. I am very excited to see your ideas, I will open up a branch just for you.

**Comment by jacobxperez** [comment]
@Mstanic05 The [css-color-system](https://github.com/jacobxperez/rams/tree/css-color-system) branch is ready

**Comment by jacobxperez** [comment]
@Mstanic05 Thanks for your support I will now work on my own implementation
